name: Test pyglider
on: [push, pull_request]
jobs:
  test-gliders:
    name: jmkdata (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: jmkdata
          environment-file: jmkdata/tests/environment.yml
          python-version: ${{ matrix.python-version }}
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: install jmkdata
        shell: bash -l {0}
        run: which pip; pip install -e .
      - name: Run tests
        shell: bash -l {0}
        run: which python; pytest
